name: Debugger Plugin CI
on: [push, pull_request]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true  # Cancel in-flight jobs for the same branch or PR

env:
    WDCLI_CACHE: "build-wdcli"
    WABT_CACHE: "build-wabt"

jobs:
    formatting-check:
        name: ESLint
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 14

            - name: Install Node.js dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint
    
    build-wdcli:
        name: Build WARDuino CLI
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive
    
            - name: Retrieve version
              run: |
                cd WARDuino
                echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_STATE
              id: version

            - name: Cache build files
              id: cache-wdcli
              uses: actions/cache@v2
              with:
                path: |
                    ./WARDuino/build-emu
                key: ${{ env.WDCLI_CACHE }}-${{ steps.version.outputs.COMMIT }}
            
            - name: Build from source
              if: steps.cache-wdcli.outputs.cache-hit != 'true'
              run: |
                cd WARDuino; mkdir build-emu; cd build-emu
                cmake .. -D BUILD_EMULATOR=ON
                make

            - name: Verify version
              if: steps.cache-wdcli.outputs.cache-hit != 'true'
              run: ./WARDuino/build-emu/wdcli --help

    build-wabt:
        name: Build custom WABT
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: recursive
    
            - name: Retrieve version
              run: |
                cd WABT
                echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_STATE
              id: version

            - name: Cache build files
              id: cache-wabt
              uses: actions/cache@v2
              with:
                path: |
                    ./WABT/build
                key: ${{ env.WABT_CACHE }}-${{ steps.version.outputs.COMMIT }}
            
            - name: Build from source
              if: steps.cache-wabt.outputs.cache-hit != 'true'
              run: |
                cd WABT; mkdir build; cd build
                cmake ..
                cmake --build .

            - name: Verify version
              if: steps.cache-wabt.outputs.cache-hit != 'true'
              run: ./WABT/build/wasm-objdump --version

    test:
        name: Mocha Test Suites
        needs: [build-wabt, build-wdcli]
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 14

            - name: Install Node.js dependencies
              run: npm ci

            - name: Get WABT cache
              id: cache-wabt
              uses: actions/cache@v2
              with:
                path: |
                    ./WABT/build
                key: ${{ env.WABT_CACHE }}-${{ steps.version.outputs.COMMIT }}

            - name: Update $PATH
              run: echo "${GITHUB_WORKSPACE}/WABT/build" >> $GITHUB_PATH

            - name: Check wat2wasm
              run: wat2wasm --version

            - name: Check wasm-objdump
              run: wasm-objdump --version

            - name: Get WARDuino cache
              id: cache-wdcli
              uses: actions/cache@v2
              with:
                path: |
                    ./WARDuino/build-emu
                key: ${{ env.WDCLI_CACHE }}-${{ steps.version.outputs.COMMIT }}

            - name: Run tests
              run: npm run test

